# -*- coding: utf-8 -*-
"""SPOILERI. Ostatak poglavlja rješenja na hrvatskom."""

CHAPTERS = [
    {"title": "Jedanaest minuta u mraku", "html":
        "<ol>"
        "<li><strong>19:41, Basel.</strong> U hodniku vagona 2, pred barunom i još troje putnika, carinik pregledava pištolj "
        "Margit Delorme i vraća ga u njezinu nezaključanu kutiju za toaletni pribor.</li>"
        "<li><strong>22:05.</strong> Delorme uzima veronal i za Stoffelom stavlja lanac na vrata. Margit se iskrada u Raoulov kupe "
        "u vagonu 1, a njezin ostaje prazan, s vratima između kupea otvorenima s obje strane, kao i uvijek.</li>"
        "<li><strong>22:10.</strong> Stoffel napušta mjesto zbog grappe u smočnici. Hodnik vagona 2 je prazan: Barić je u "
        "prtljažnom vagonu, Pryor i Klara u salonskom, Eglijevi i dr. Wirz spavaju.</li>"
        "<li><strong>Oko 22:20.</strong> Barun iz broja 9 ulazi u Margitin prazan kupe i uzima pištolj iz kutije za toaletni "
        "pribor.</li>"
        "<li><strong>22:24.</strong> Nokturno ulazi u tunel Grauhorn. Jedanaest minuta tutnjava pare i kamena guta sve.</li>"
        "<li><strong>Oko 22:26.</strong> Otvara vrata između kupea. Delorme spava. Pritišće mu jastuk na lice i puca jednom.</li>"
        "<li><strong>Oko 22:29.</strong> Natrag u broju 6 spušta prozor i baca pištolj u mrak. Pri 48 km/h, pet minuta nakon "
        "ulaska, pada 3,9 km od portala. Dim i čađa kuljaju unutra; prozor ostavlja spuštenim, a dva mu pera iz jastuka padaju "
        "s rukava na pod.</li>"
        "<li><strong>22:31.</strong> Već je u svom kupeu. U salonskom vagonu Kesslerova bljeskalica hvata madame Duclos samu sa "
        "svojim čajem.</li>"
        "<li><strong>22:40.</strong> Barić kuca na broj 5 sa sudskim spisima. Nitko ne odgovara: Delorme je već mrtav.</li>"
        "<li><strong>22:52.</strong> Margit se vraća u leden, čađav kupe, zatvara prozor i liježe ne otvorivši vrata između "
        "kupea.</li>"
        "<li><strong>23:15.</strong> Barun sjeda kod madame Duclos i pita je koliko je sati.</li>"
        "<li><strong>00:14, Sankt Oswin.</strong> Pokušava preuzeti župnikovo pismo, na narječju doline u kojoj je odrastao. "
        "Šef postaje ga odbija.</li>"
        "</ol>"},
    {"title": "Sat koji se nikad nije dogodio", "html":
        "<p>Negdje između Basela i salonskog vagona barun je primijetio da sat madame Duclos kasni sat vremena. Bio je to sat "
        "njezina pokojnog muža i još je pokazivao francusko vrijeme: nitko ga nije pomaknuo na granici, kako traži vozni red. "
        "Kapi je uzela „osam minuta do sedam“ dok je vlak kretao iz Basela u 19:52, a prvi čaj „oko devet i dvadeset“, što je "
        "sat na baru otisnuo kao 22:20.</p>"
        "<p>U 23:15 po svim ostalim satovima u vlaku barun je sjeo za njezin stol i pitao je koliko je sati. Njezin je sat "
        "pokazivao deset i četvrt. Odmah je naručio konjak i kamilicu, a sat na baru otisnuo je račun 47 u 23:17. Pola je sata "
        "pričao o Andama i pri odlasku opet pitao koliko je sati: petnaest do jedanaest.</p>"
        "<p>Poštena starica, precizan sat, gospodin koji dvaput pita koliko je sati. Od toga je nastao alibi za razdoblje od "
        "22:15 do 22:45, upravo onih pola sata u kojem je Delorme umro, a svaka je riječ bila istinita osim sata.</p>"
        "<p>Tri ga dokumenta rastavljaju. Na ploči 12, u 22:31 po satu u salonu, ona sjedi sama s jednom šalicom, a njezin "
        "otvoreni sat pokazuje 21:31. Račun 47 otisnut je u 23:17. A vozni red polazak iz Basela, koji ona pamti kao „osam minuta "
        "do sedam“, bilježi u 19:52.</p>"},
    {"title": "Tragovi koji vode do njega", "html":
        "<ul>"
        "<li>Kad je lanac bio stavljen, u broj 5 moglo se ući samo kroz kupe 6, a kupe 6 bio je prazan od 22:05 do 22:52.</li>"
        "<li>Hitac je ispaljen u tunelu: pištolj je ležao 3,9 km u njemu, a čađa je zacrnila prozorsku dasku broja 6. Za tih "
        "jedanaest minuta svakog drugog osumnjičenog netko tko nema razloga lagati smješta negdje drugdje.</li>"
        "<li>Njegov je alibi pomaknut za sat.</li>"
        "<li>Dešnjak je, a ljevakov sat nosi na krivom zglobu; nije znao pokrenuti repetitor; a njegovi inicijali na ugovoru "
        "nagnuti su na drugu stranu od potpisa na barunovoj narudžbi iz 1931.</li>"
        "<li>Vršak prsta koji je „izgubio u padu“ nedostaje već na fotografiji iz 1934., na vodičevoj ruci, dok pravi barun "
        "nosi sat na desnom zglobu.</li>"
        "<li>Govori njemački Oswinske doline i španjolski iz udžbenika.</li>"
        "<li>U 00:14 pokušao je preuzeti župnikovo pismo, a u 02:55 krzneni mu je ovratnik još bio mokar od snijega s perona.</li>"
        "<li>Župnik Casutt: Gredig je bio dešnjak, a čovjek u Gredigovu grobu imao je ljevakov žulj od pera.</li>"
        "</ul>"},
    {"title": "Zašto to nisu bili ostali", "html":
        "<ul>"
        "<li><strong>Margit Delorme</strong> imala je svoj pištolj, svoja vrata, svoju čađu i laž o migreni. Ali od 22:05 do "
        "22:52 bila je u Raoulovu kupeu u vagonu 1. Poslužitelj vagona 1 zabilježio je damu u srebrnom krznu, poderana poruka "
        "poslala ju je na vagon 1, vrata 3, a tijekom tunela nitko nije prešao iz vagona 1 u vagon 2. Svatko tko je stajao u "
        "hodniku u Baselu znao je gdje drži pištolj.</li>"
        "<li><strong>Raoul Delorme</strong> imao je svađu, krivotvoreni ček i pola imovine po staroj oporuci. Ali otac mu je bio "
        "živ u 22:05, nakon svađe, a Raoul nakon 21:55 nije napuštao vagon 1.</li>"
        "<li><strong>Tomislav Barić</strong> imao je prijetnju, zlu krv, igle i kucanje u 22:40. Ali cijeli je tunel proveo u "
        "prtljažnom vagonu s kondukterom, lanac na broju 5 ne može se podići s hodnika, a na kucanje se nitko nije javio jer je "
        "Delorme već bio mrtav.</li>"
        "<li><strong>Emil Stoffel</strong> imao je četvrtasti ključ, pritužbu i laž o svom mjestu. Ali ključ ne svladava lanac, "
        "a on je bio u smočnici s kuharom, na ploči 11 u 22:26.</li>"
        "<li><strong>Constance Pryor</strong> imala je sestru, pisma, ukosnicu ispod ležaja i laž da ga nikad nije upoznala. "
        "Ali kupe je pretražila za večere, dok je Delorme sjedio za stolom, a u 22:31 je za šankom na ploči 12, s dva računa kao "
        "dokazom.</li>"
        "<li><strong>Klara Imhof</strong> bila je njegova tajna kći. Ali njegova ju je smrt stajala svega, jer nova oporuka "
        "nikad nije potpisana, a ona je na ploči 12 za pisaćim stolom.</li>"
        "</ul>"},
    {"title": "Epilog", "html":
        "<p>Ralica se probila iz Pradelle u subotu ujutro u devet i deset. Do tada je inspektor Tscharner već doveo župnika "
        "Casutta na postaju. Svećenik je dugo gledao čovjeka s krznenim ovratnikom, a onda tiho rekao: „Kaspare.“ Čovjek koji se "
        "nazivao Friedrichom von Aschauom nije rekao ništa. Zatim je pitao smije li vidjeti crkvu prije nego što ga odvedu niz "
        "dolinu.</p>"
        "<p>U proljeće je grob u Sankt Oswinu otvoren i nad Friedrichom von Aschauom postavljen je kamen s pravim imenom. "
        "Delorme &amp; Cie nikad nije prodan. Sud u Beču presudio je u korist Tomislava Barića, čije ime sada stoji uz ime "
        "Casimira Delormea na patentu. A Klara Imhof, koja ništa nije mogla dokazati, dobila je pismo od Raoula Delormea kojim "
        "joj daje trećinu svojih dionica, „jer bi to stari potpisao“.</p>"
        "<p>Sat br. 7031 vratio se kući u La Chaux-de-Fonds. I danas otkucava četvrti, svakome tko zna gdje je klizač.</p>"
        "<p>Inspektor Tscharner zahvaljuje vam i šalje bocu kuharove grappe za sljedeći put kad budete prolazili kroz tunel.</p>"},
]
